config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events, except: [:index] do
    resources :comments, only: [:create]
    resources :pictures, only: [:create]
  end

  devise_for :users do
    resources :profile_pictures, only: [:create]
  end

  resources :users, only: [:show]
  resources :participations, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :categories, only: [:show, :index] 
  resources :conversations do
    resources :messages
   
  end

  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #Callbacks
  before_save :default_values
  after_create :welcome_send

  #Associations
  belongs_to :department
  has_many :administrated_events, foreign_key: 'administrator_id', class_name: "Event", dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :attended_events, through: :participations, source: :event, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :profile_picture, dependent: :destroy

  # A user can or can't have followers. We're using the Friendship table to join a follower to a user
  # who is identify by his id
  has_many :active_friendships, class_name: "Friendship", foreign_key: "follower_id", dependent: :destroy

  #Same as the follower relation. A user can decided to follow an other user.
  has_many :passive_friendships, class_name: "Friendship", foreign_key: "followed_id", dependent: :destroy

  # using following make more sense for the users that an other one follow because the word followers
  # is better for the users that follows an other one. We're using the active_friendships to found the user
  # to follow/unfollow
  has_many :following, through: :active_friendships, source: :followed

  #Same as the following relation but the opposite
  # For more clarity ze're using has_many :followers instead of :follower
  has_many :followers, through: :passive_friendships, source: :follower

  #Validations
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: ": Please enter a valid email format" }  #phone number format also accepts 'N/A', in case it's been set as default value at registration time and not changed when updating
  validates :phone_number, format: { :allow_blank => true, with: /\A(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})|N\/A\z/, message: "Please enter a valid number (french format)" }
  validates :department, presence: {:message => ": Please choose a department" }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validate :profile_picture_limit_check


  def age  #calculate a user age based on it's date_ob_birth attribute. Set to N/A if no date submitting
    self.date_of_birth.nil? ? "N/A" : ((Time.zone.now - self.date_of_birth.to_time) / 1.year.seconds).floor
  end

  def follow(user)
    active_friendships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_friendships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

private

  def default_values   # set default values for fields left blank when submitting
    self.phone_number = "N/A" if self.phone_number.blank?
    self.description = "No description available" if self.description.blank?
  end

  def profile_picture_limit_check
    if profile_picture.attached?
      if profile_picture.blob.byte_size > 2000000
        profile_picture.purge
        errors[:base] << "The picture should be smaller than 2Mo"
      end
    end
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url(images/hero_1.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-10" data-aos="fade-up" data-aos-delay="400">
        <div class="row justify-content-center mt-5">
          <div class="col-md-8 text-center">
            <h1>Profile</h1>
            <p class="mb-0"></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br/>
<br/>
<br/>
<div class="site-section">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">
        <% if @user.profile_picture.attached? %>
          <%= image_tag @user.profile_picture.variant(combine_options: {resize: '500x500^', extent: '500x500', gravity: 'Center'}) ,alt: 'User profile picture', class: "img-fluid rounded" %>
        <% else %>
          <img src="/assets/user_default.png" alt="" class="img-responsove border-raduis-3">
        <% end %>
      </div>
      <div class="col-md-5 ml-auto">
        <h2 class="text-primary mb-3">
          <% if user_signed_in? && @user != current_user %>
            <% if current_user.following?(@user) %>
              <%= button_to "Unfollow", friendship_path(user_id: @user.id) , method: :delete, :class =>"btn btn-lg btn-primary rounded btn-danger col-3" %>
            <% else %>
              <%= button_to "Follow", friendships_path(user_id: @user.id), :class =>"btn btn-lg btn-primary rounded btn-block col-3" %>
            <% end %>
            <%= render "components/informations_users" %>

          <% end %><br>
        </div>
      </div>
    </div>
    <br/>
    <br/>
    <br/>

    <div class="container"></div><br>

    <div class="container">
      <div class="row align-items-start">
        <div class="col">
          <div class="row mb-5">
            <div class="col-md-4 text-left border-primary">
              <h2 class="font-weight-light text-primary pb-3">Attended Events</h2>
            </div>

          </div>

          <div class="events_attendees">
            <% @user.attended_events.each  do |event|  %>

              <div class="card" style="width: 20rem;">
                <h5 class="card-body">
                  <%= event.title %>
                </h5>
                <p class="card-text text-center">
                  <%= event.start_date %>
                </p>
                <p class="card-text  text-center">
                  <%= event.department.name %>
                </p>

              </div><br>
            <% end %>

          </div>

        </div>
        <div class="col">
          <div class="row mb-5">
            <div class="col-md-4 text-left border-primary">
              <h2 class="font-weight-light text-primary pb-3">Events Create</h2>
            </div>

          </div>

          <div class="events_created">
            <% @user.administrated_events.each  do |event|  %>

              <div class="card" style="width: 20rem;">
                <h5 class="card-body">
                  <%= event.title %>
                </h5>
                <p class="card-text  text-center">
                  <%= event.start_date %>
                </p>
                <p class="card-text  text-center">
                  <%= event.department.name %>
                </p>

              </div><br>
            <% end %>

          </div>
        </div>
      </div>
    </div>