config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events, except: [:index] do
    resources :comments, only: [:create]
    resources :pictures, only: [:create]
  end

  devise_for :users do
    resources :profile_pictures, only: [:create]
  end

  resources :users, only: [:show]
  resources :participations, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :categories, only: [:show, :index] 
  resources :conversations do
    resources :messages
   
  end

  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'
end

app/models/event.rb
class Event < ApplicationRecord
  #Associations
  belongs_to :department
  belongs_to :category
  belongs_to :administrator, class_name: "User"
  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, source: :user, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :picture, dependent: :destroy

  #Validations
  validate :start_date_cannot_be_in_the_past
  validate :positif_multiple_of_5
  validates :duration, numericality: { only_integer: true }
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 5..1000 }
  validates :location, presence: true
  validates :department, presence: {:message => "must be selected" }
  validate :event_picture_limit_check

  #Scopes
  scope :ten_most_recent, -> { order(created_at: :desc).limit(10) }
  scope :five_random_selection, -> { reorder("RANDOM()").limit(5) }
  scope :in_department, -> (department) {where(department_id: department)}
  scope :in_categories, -> (categories) {where(category_id: categories)}

  #Pagination
  self.per_page = 6

  def number_of_places_available
    self.max_participants - self.participants.count
  end

  def has_place_available?
    self.number_of_places_available  > 0
  end

  def starting_date
    self.start_date.strftime("%d-%m-%Y") + " at " + self.start_date.strftime("%H:%M")
  end

  def has_participant?(user) #return true if the user passed as argument is participant
    self.participants.include?(user)
  end

  def is_administrated_by?(user)
    self.administrator == user
  end

  def administrator_full_name
    self.administrator.first_name + " " + self.administrator.last_name
  end

  def is_still_ongoing?
    DateTime.parse("#{self.start_date}") >= DateTime.now.change(offset: "+0000")
  end

private

  def start_date_cannot_be_in_the_past
     errors.add(:start_date, ": time and date must be present or can't be in the past") unless start_date.present? && DateTime.parse("#{start_date}") >= DateTime.now.change(offset: "+0000")
  end

  def positif_multiple_of_5
    errors.add(:duration, "must be a multiple of 5") unless duration.present? && duration > 0 && duration % 5 == 0
  end

  def event_picture_limit_check
    if picture.attached?
      if picture.blob.byte_size > 2000000
        picture.purge
        errors[:base] << "The picture should be smaller than 2Mo"
      end
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	include EventsHelper
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_event, only: [:show, :edit, :update, :destroy]
	before_action :restrict_access_to_administrator, only: [:edit, :update, :destroy]

	def index
		@events = Event.page(params[:page]).order('created_at DESC')
		@hand_selected_events = Event.in_categories(current_user_3_best_categories_of_interest).in_department(current_user.department).ten_most_recent.five_random_selection if user_signed_in?
		@categories = Category.all


	end

	def new
		@event = Event.new
	end

	def create        #adds start_date attribute to the events params and associate the current user to the event being created
		@event = Event.new(event_params.merge(start_date: parsed_date_and_time, administrator: current_user))
		if @event.save
			flash[:success] = "Event Successfully Created !"
			redirect_to @event
		else
			flash[:danger] = "Your event hasn't been created"
			render :new
		end
	end

	def show
		@event = set_event
		@comment = Comment.new
		@comments = @event.comments.order("created_at DESC")
		#comments will appear on descending order (the last comment will be the first etc..)
	end

	def edit
		@event = set_event
	end

	def update
		@event = set_event
		if @event.update(event_params.merge(start_date: parsed_date_and_time))
			flash[:success] = "Your modifications have been saved successfully"
			redirect_to @event
		else
			flash[:error] = "Your modifications haven't been saved"
			render :edit
		end
	end

	def destroy
		set_event.destroy
		flash[:success] = "Your event has been deleted successfully"
		redirect_to root_path
	end

private

  def set_event
    @event = Event.find(params[:id])
  end

	def restrict_access_to_administrator  #check if the event subject of the action (thanks to its id in params) is owned by the current user, redirect to root_path otherwise
		redirect_to root_path, notice: "Action can't be performed, you are not the event's creator" unless current_user.id == set_event.administrator.id
	end

  def event_params
    params.require(:event).permit(:title, :description, :duration, :location, :category_id, :department_id, :max_participants, :picture)
	end

	def parsed_date_and_time
		date = params.require(:event).permit(:start_date)  #construction of full event's starting time (date + time) by parsing them through DateTime()
	  time = params.permit(:time) 	          					 #after getting each one separatly through the form
		params[:time].empty? ? nil : DateTime.parse("#{date} #{time}")
	end    #We purposely raise date_time's validation by returning nil as its attribute's value if no time is given
end

app/helpers/events_helper.rb
module EventsHelper
  def current_user_3_best_categories_of_interest
    most_recent_liked_events = current_user.liked_events.ten_most_recent
    arr_of_ids_of_categories_of_interest = most_recent_liked_events.map do |event|
      event.category.id   # return array of ids of the 10 most recent events that have been liked by current user
    end                   # A same category may appears multiple times

    ids_occurences_counter_hash = Hash.new(0)

    arr_of_ids_of_categories_of_interest.each do |id|
      ids_occurences_counter_hash[id] += 1  #Count how many times appears each category
    end
      #We sort and take the 3 categories ids that appear the most
    ids_occurences_counter_hash.sort_by { |_, v| -v }.take(3).map { |arr| arr[0] }
  end
end

app/views/events/edit.html.erb
<div class="site-section bg-light">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-11 mb-3 mt-5" data-aos="fade">
        <% if @event.errors.any? %>
        <div class="alert alert-warning" role="alert">
          <p>
            Your event could not be modified! Please check the following errors :
          </p>
          <ul>
            <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="row">
          <div class="col-3 border-primary ">
            <h2 class="font-weight-light text-primary display-2">Update your event</h2>
            <h1><mark><%= @event.title %></mark></h1>
          </div>
          <div class='col-9'>
            <%= render "components/form-event" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%= render "components/search_top" %>
<div class="site-section bg-light">
  <div class="container">
    <div class="overlap-category mb-4">
    <%= render 'components/categories' %>
  </div>
    <div class="site-section" data-aos="fade">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-5 border-primary ">
            <h2 class="font-weight-light text-primary display-1">Better together</h2>
            <p>
              ShareMyHobby is a platform for finding and building local communities. People use ShareMyHobby learn new things, meet new people, challenge themselves, and pursue their passions, together.
            </p>
          </div>
          <div class="col-6 img-fluidfloat-right w-10">
            <%= image_tag "front-image.jpg" %>
          </div>
        </div>
        <%= render 'components/card_interest_you' %>

        <div class="row justify-content-center mb-4 align-items-center">
          <div class="col-md-7 text-center border-primary">
            <br>
            <br>
            <h2 class="font-weight-light text-primary">Latest Events</h2>
            <p class="color-black-opacity-5">
              Join the latest events around!
            </p>
          </div>
        </div>
        <div class="container">
        <div class="pagination">
          <div class="row">
            <%= render 'components/event_card' %>
          </div>
        </div>
          <div class="text-center">
            <%= will_paginate @events, renderer: BootstrapPagination::Rails %>
          </div>
        </div>
     
          <div class="text-center">
            <%= link_to "See more events!", categories_path, class: "btn-primary btn-lg round" %>

          </div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/events/new.html.erb
<div class="site-section bg-light">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-11 mb-3 mt-5" data-aos="fade">

        <% if @event.errors.any? %>
          <div class="alert alert-warning" role="alert">
            <p>Votre événement n'a pas pu être crée pour la (ou les) raison(s) suivante(s) :</p>
            <ul>
              <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row">
          <div class="col-3 border-primary ">
            <h2 class="font-weight-light text-primary display-2">Create an event</h2>

            <p>Share Your Hobby & Meet new Fellows that Share the same Passion !</p>

          </div>

          <div class='col-9'>
            <%= render "components/form-event" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url(images/hero_1.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-10" data-aos="fade-up" data-aos-delay="400">
        <div class="row justify-content-center mt-5">
          <div class="col-md-8 text-center">
            <h1>
              <%= @event.title%></h1>
            <p class="mb-0"></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="mb-4">
          <div class="listing-item">
            <div class="listing-image">
              <div>
                <% if @event.picture.attached? %>
                  <%= image_tag @event.picture.variant(combine_options: {resize: '500x500^', extent: '500x500', gravity: 'Center'}) %>
                <% end %>
              </div>
              <div class="listing-item-content">
                <% if user_signed_in? %>
                  <% if liked?(@event) %>
                    <%= link_to like_path(id: @event, like_id: liked?(@event)), class: "bookmark", method: :delete do %>
                      <span class="icon-heart" style="color:red;">
                        <center><%= @event.likes.count %></center>
                      </span>
                    <% end %>
                  <% else %>
                    <%= link_to likes_path(id: @event.id), class: "bookmark", method: :post do %>
                      <span class="icon-heart">
                        <center>
                          <%= @event.likes.count %>
                        </center>
                      </span>
                    <% end %>
                  <% end %>
                <% end %>
                </div>
            </div>
          </div>
        </div>
        <%= render "components/tablist"%>
        </div>
        <%= render "components/card_user_event"%>
    </div>
  </div>
</div>